site_name: Modinator
site_description: The official website and documentation for the Modinator Discord Bot
site_url: http://modinator.tk
site_author: Devin Conway
repo_url: https://github.com/TheConwayy/Modinator-docs

theme:
  name: null
  custom_dir: 'cinder'
  disable_footer: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installiation:
    - Configuration: config.md
  - Commands:
    - Help Commands: 'help-commands.md'
    - Moderation Commands: 'mod-commands.md'
    - Utility Commands: 'utility-commands.md'
  - Modinator LITE:
    - About: 'about-lite.md'
    - Download: 'download-lite.md'
    - Commands: 'lite-commands.md'
